dist: bionic

language: node_js
node_js:
  - "lts/*"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm ci --only-production

script:
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  - npm run e2e
