version: 2.1
orbs:
  node: circleci/node@3.0.0
  browser-tools: circleci/browser-tools@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
